version: "3.10"

services:
  app:
    build: .
    image: mini-saas:latest
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: minisaas
      POSTGRES_USER: mini
      POSTGRES_PASSWORD: mini
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: minisaas
      POSTGRES_USER: mini
      POSTGRES_PASSWORD: mini
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: