name: CI/CD Pipeline
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    # Checkout source code
    - name: Checkout code
      uses: actions/checkout@v4
 
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
 
    # Build Docker image
    - name: Build Docker image
      run: docker build -t mini-saas-2 .
 
    # (Optional) Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker tag mini-saas-2 ${{ secrets.oltik1 }}/mini-saas-2:latest && docker push ${{ secrets.oltik1 }}/mini-saas-2:latest
 
    # (Optional) Deploy to remote server via SSH
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.oltik1 }}/mini-saas-2:latest
          docker stop mini-saas || true
          docker rm mini-saas || true
          docker run -d -p 5000:5000 --name mini-saas ${{ secrets.oltik1 }}/mini-saas-2:latest
